name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Docker image
      run: |
        docker build -t backend-image .
    
    #- name: Push to Docker Hub
    #  if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    #  env:
    #    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    #  run: |
    #    echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    #    docker tag backend-image $DOCKER_USERNAME/backend-image:latest
    #    docker push $DOCKER_USERNAME/backend-image:latest